# 5. Sequences

In [78]:
from datascience import *
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, baseline_high - 0.093,
                   baseline_high + 0.105, baseline_high + 0.684)
highs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [79]:
import numpy as np
baseline_high = 14.48
highs = np.array([baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684])
highs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [80]:
sum(highs)/len(highs)

14.434000000000001

# 5.1. Arrays

In [81]:
english_parts_of_speech = make_array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")
english_parts_of_speech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'],
      dtype='<U12')

In [82]:
type(english_parts_of_speech)

numpy.ndarray

In [83]:
english_parts_of_speech = np.array(["noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection"])
english_parts_of_speech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'],
      dtype='<U12')

In [84]:
type(english_parts_of_speech)

numpy.ndarray

In [85]:
import numpy as np
baseline_high = 14.48
highs = np.array([baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684])
highs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [86]:
(9/5) * highs + 32

array([ 56.48  ,  57.8966,  58.253 ,  59.2952])

In [87]:
highs.prod()

43274.231214608

In [88]:
highs.size

4

In [89]:
highs.sum()

57.736000000000004

In [90]:
highs.mean()

14.434000000000001

In [91]:
import numpy as np

In [92]:
numbers = np.array([0, 1, 2, 3, 4, 5])
numbers

array([0, 1, 2, 3, 4, 5])

In [93]:
numbers.all()

False

In [94]:
numbers.any()

True

In [113]:
np.count_nonzero(numbers)

5

## input: array, output: single value

In [114]:
np.prod(numbers)

0

In [115]:
np.sum(numbers)

15

In [116]:
np.mean(numbers)

2.5

In [117]:
np.size(numbers)

6

# all 0이 없으면 true

In [20]:
np.all(numbers)

False

In [21]:
n2 = np.array([1, 1, 2, 3, 4, 5])
np.all(n2)

True

In [22]:
n3 = np.array([0, 1, 2, 3, 4, 5])
np.all(n3)

False

In [23]:
np.any(numbers)

True

In [24]:
np.count_nonzero(numbers)

5

## input: array, output: array

In [118]:
numbers = np.array([1.4,2.5,3.6,2.7,5.6])

In [119]:
np.diff(numbers)

array([ 1.1,  1.1, -0.9,  2.9])

In [120]:
print(numbers.size,np.diff(numbers).size) 

5 4


In [121]:
np.round(np.array([1.4,2.5,3.6,2.7,5.6]))

array([ 1.,  2.,  4.,  3.,  6.])

In [122]:
np.cumprod(numbers)

array([   1.4  ,    3.5  ,   12.6  ,   34.02 ,  190.512])

In [30]:
np.cumsum(numbers)

array([  1.4,   3.9,   7.5,  10.2,  15.8])

In [31]:
np.exp(numbers)

array([   4.05519997,   12.18249396,   36.59823444,   14.87973172,
        270.42640743])

In [32]:
np.log(numbers)

array([ 0.33647224,  0.91629073,  1.28093385,  0.99325177,  1.7227666 ])

In [33]:
np.sqrt(numbers)

array([ 1.18321596,  1.58113883,  1.8973666 ,  1.64316767,  2.36643191])

In [34]:
np.sort(numbers)

array([ 1.4,  2.5,  2.7,  3.6,  5.6])

## input: string array

In [141]:
strArr = np.array(["one" , "two" , " THREE", "4", "five "])

In [142]:
np.char.lower(strArr)

array(['one', 'two', ' three', '4', 'five '],
      dtype='<U6')

In [143]:
np.char.upper(strArr)

array(['ONE', 'TWO', ' THREE', '4', 'FIVE '],
      dtype='<U6')

In [144]:
np.char.strip(strArr)

array(['one', 'two', 'THREE', '4', 'five'],
      dtype='<U6')

In [145]:
np.char.isalpha(strArr)

array([ True,  True, False, False, False], dtype=bool)

In [146]:
np.char.isnumeric(strArr)

array([False, False, False,  True, False], dtype=bool)

## input: string array, search array

In [152]:
strArr = np.array(["one" , "two" , "  three", "4", "five "])

In [153]:
np.char.count(strArr,"t")

array([0, 1, 1, 0, 0])

In [154]:
np.char.find(strArr,"o")

array([ 0,  2, -1, -1, -1])

In [155]:
np.char.rfind(strArr,"e")

array([ 2, -1,  6, -1,  3])

In [156]:
np.char.startswith(strArr,"t")

array([False,  True, False, False, False], dtype=bool)

# 5.2. Range

In [46]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [47]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [48]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [49]:
np.arange(3, 30, 5)

array([ 3,  8, 13, 18, 23, 28])

In [50]:
np.arange(1.5, -2, -0.5)

array([ 1.5,  1. ,  0.5,  0. , -0.5, -1. , -1.5])

## Example: Leibniz's formula for PI

In [51]:
by_four_to_20 = np.arange(1, 20, 4)
by_four_to_20

array([ 1,  5,  9, 13, 17])

In [52]:
positive_term_denominators = np.arange(1, 10000, 4)
positive_term_denominators

array([   1,    5,    9, ..., 9989, 9993, 9997])

In [53]:
positive_terms = 1 / positive_term_denominators

In [54]:
negative_terms = 1 / (positive_term_denominators + 2)

In [55]:
4 * ( sum(positive_terms) - sum(negative_terms) )

3.1413926535917955

# 5.3. More on Arrays

In [56]:
baseline_high = 14.48
highs = np.array([baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684])
highs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [57]:
baseline_low = 3.00
lows = np.array([baseline_low - 0.872, baseline_low - 0.629,
                  baseline_low - 0.126, baseline_low + 0.728])
lows

array([ 2.128,  2.371,  2.874,  3.728])

In [58]:
make_array(
    highs.item(0) - lows.item(0),
    highs.item(1) - lows.item(1),
    highs.item(2) - lows.item(2),
    highs.item(3) - lows.item(3)
)

array([ 11.472,  12.016,  11.711,  11.436])

In [59]:
highs - lows

array([ 11.472,  12.016,  11.711,  11.436])

## Example: Walli's Formula for PI

In [60]:
even = np.arange(2, 1000001, 2)
one_below_even = even - 1
one_above_even = even + 1

In [61]:
2 * np.prod(even/one_below_even) * np.prod(even/one_above_even)

3.1415910827951143